- hosts: all
  gather_facts: true
  roles:
    - role: DataDog.datadog
      become: true  
      when: 
        - inventory_hostname in groups["webservers"]
  pre_tasks:
    - name: Ping
      ansible.builtin.ping:
  tasks:

    - name: Create a network
      community.docker.docker_network:
        name: redme-net
      become: true

    - name: Create a redme container
      community.docker.docker_container:
        name: app
        image: redmine:5.1.6-alpine3.21
        state: started
#        recreate: true
        restart_policy: always
        links:
          - "postgres-db:db"        
        ports:
          - 80:3000
        volumes:
          - /usr/src/redmine/files:/usr/src/redmine/files
        env_file: /usr/src/redmine/files/redmine.env
        networks:
          - name: redme-net
      become: true  
    # - name: Create a data container
    #   community.docker.docker_container:
    #     name: postgres-db
    #     image: postgres:15.10
    #     state: started
    #     recreate: true
    #     restart_policy: always
    #     ports:
    #       - "5432:5432"
    #     env:
    #       POSTGRES_DB: redmine-db
    #       POSTGRES_USER: redmine-user
    #       POSTGRES_PASSWORD: password
    #     networks:
    #       - name: redme-net
    #         aliases:
    #           - db
    #   become: true  

#     - name: Create a redme container
#       community.docker.docker_container:
#         name: app
#         image: redmine:5.1.6-alpine3.21
#         state: started
# #        recreate: true
#         restart_policy: always
#         links:
#           - "postgres-db:db"        
#         ports:
#           - 80:3000
#         volumes:
#           - /usr/src/redmine/files:/usr/src/redmine/files
#         env_file: /usr/src/redmine/files/redmine.env
#         # - path: /usr/src/redmine/files/redmine.env
#         #   required: true # default        
#         # env: # Настраиваем
#         #   REDMINE_DB_POSTGRES: postgres-db
#         #   REDMINE_DB_PORT: "5432"
#         #   REDMINE_DB_USERNAME: redmine-user
#         #   REDMINE_DB_PASSWORD: password
#         #   REDMINE_DB_DATABASE: redmine-db
#         #   REDMINE_SECRET_KEY_BASE: "supersecretkey"

#         networks:
#           - name: redme-net
#       become: true

